language: c

before_install:
          - sudo apt-get update -qq
          - sudo apt-get install -y automake make libtool autoconf rpm cmake libssl-dev libxml2-dev libboost-all-dev libstring-crc32-perl 
          - pip install --user codecov

script: mkdir build && cd build && cmake ../ -DCMAKE_VERBOSE_MAKEFILE=TRUE -DCMAKE_BUILD_TYPE=COVERAGE -DWITH_CLI=FALSE -DWITH_UT_ROOT=FALSE && make -j4 && ctest -V

after_success:
        - codecov

