language: c

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "BKEWkWMezG7nELzU61GwOS9ZzJdWTLBTJG7CNMkPktkOIWoPP1xRmh/GGLCkM6+946sb/6qzAF+TzfmNujw4QcSavT/K1Va+VHGSsQnPM02IxCjRJjW50f41k6NoMRCp+0+OA6qMaGM3WyqNDiXwOZaf3X7VoQoZeTk53n1wnPnFmRwx352UilOKdHzRN6unc7S1VPWVorOI3w7Fxldm2ipg4+tW2eL2nyFhxOxstITIWljGBItskkGqwGwatODeFf7aY9Phg7ab2d4YkyeFHyy7ewzHBQlKQ3ZDbw+7dX8a2pR5WomYsK9G8twZ6Rh68b9vZiVM/c508cTk0KXysU2mjdfGeS73xATuNAc7Wqp0ohQYLb3U0iYHYSrfzMICW8YaHSe0ZNja6mXqJl8jemqiiJjozjFAEg95qwMlJJ1Xhx6/j0auM5JCy2nC6wKj5qsH8G8W2/tb3EsvLg/nyxrsU7GvY9ze3shdZR3OCEH4LCFEzLF/0Rr87F3ILsbzV7JED6rsSNqJW2XTgcnb0oD+WUAUk2w/qLPYASpOtk7jMimc0JvvQAE6/UJmgofN504+17pIDABd7E7zLQ9bOIPTsW8vpx5Rkjg4frHbuYr2PM25C9tviXpdT+uhQaHdvrxHjz8ouSHVi+zsZfl3JDOsVYN/X60i3y5WQtb2dYA="

before_install:
          - sudo apt-get update -qq
          - sudo apt-get install -y automake make libtool autoconf rpm cmake libssl-dev libxml2-dev libboost-all-dev libstring-crc32-perl 
          - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
            #- pip install --user codecov
          #- pip install --user cpp-coveralls

script: mkdir build && cd build && cmake ../ -DCMAKE_VERBOSE_MAKEFILE=TRUE -DCMAKE_BUILD_TYPE=COVERAGE -DWITH_CLI=FALSE -DWITH_UT_ROOT=FALSE && make -j4 && ctest -V

after_success:
        #- codecov
        - coveralls --gcov-options '\-lp'
addons:
  coverity_scan:
    project:
      name: "OznOg/OpenExanodes"
      description: "Build submitted via Travis CI"
    build_command_prepend: "mkdir build && cd build && cmake ../ -DCMAKE_VERBOSE_MAKEFILE=TRUE -DCMAKE_BUILD_TYPE=COVERAGE -DWITH_CLI=FALSE -DWITH_UT_ROOT=FALSE"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan

