language: c

before_install:
          - sudo apt-get update -qq
          - sudo apt-get install -y automake make libtool autoconf rpm cmake libssl-dev libxml2-dev libboost-all-dev libstring-crc32-perl 

script: mkdir ../build && cd ../build && cmake ../OpenExanodes/ -DWITH_UT=FALSE && make -j4


