language: c cpp

compiler:
  - gcc
  - clang

before_install:
          - sudo apt-get update -qq
          - sudo apt-get install -y automake make libtool autoconf rpm cmake libssl-dev libxml2-dev libboost-all-dev libstring-crc32-perl libaio-dev

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8
    - g++-8
    - clang

script: export CC=gcc-8 && export CXX=g++-8 && mkdir ../build && cd ../build && cmake ../OpenExanodes/ -DWITH_LIBAIO=TRUE -DWITH_UT_ROOT=FALSE && make -j4 && ctest -V

