#!/usr/bin/perl
use strict;
use warnings;
use String::CRC32;

my $filename;
my $cksum;

$filename = $ARGV[0];

if (!open(FILE, "< ${filename}")) {
    exit 1;
}

$cksum = crc32(*FILE);

print "#ifndef XML_PROTOCOL_VERSION_H\n";
print "#define XML_PROTOCOL_VERSION_H\n";
print "\n\n";
print "/* This file is automatically generated. Do not edit. */\n";
print "#define XML_PROTOCOL_VERSION \"${cksum}\"\n\n\n";
print "#endif\n";

close(FILE);
