/*
 * Copyright 2002, 2009 Seanodes Ltd http://www.seanodes.com. All rights
 * reserved and protected by French, UK, U.S. and other countries' copyright laws.
 * This file is part of Exanodes project and is subject to the terms
 * and conditions defined in the LICENSE file which is present in the root
 * directory of the project.
 */

#ifndef __XML_PROTO_H
#define __XML_PROTO_H

#include "admind/src/adm_command.h"
#include "common/include/exa_config.h"

#define XPATH_TO_GET_PARAM "/Admind/command/param"

typedef void (*parse_fn_t) (struct _xmlDoc *doc, void *data, cl_error_desc_t *err_desc);

typedef struct xml_parser
{
  adm_command_code_t cmd_code;   /**< code of the command */
  const char *const  cmd_name;   /**< public name of the command (over XML)*/
  parse_fn_t         parse;      /**< parsing function to perform XML-> binary */
  size_t             parsed_params_size; /**< size of the structure the adm_command expects */
} xml_parser_t;

/* this structure is autogenerated at compilation */
extern xml_parser_t xml_parser_list[];

#endif
