#!/bin/sh
\cp /proc/virtualiseur/zones_enregistrees /tmp/liste1_zones
if [ "$1" = "1" ]
then
echo "b $2" > /proc/virtualiseur/zones_enregistrees
fi

if [ "$1" = "2" ]
then 
echo "f $2" > /proc/virtualiseur/zones_enregistrees
fi

\cp /proc/virtualiseur/zones_enregistrees /tmp/liste2_zones

no_zone=`diff /tmp/liste1_zones /tmp/liste2_zones | tail -n1 | cut -f 3 -d" "`
echo "ajout zone = $no_zone. $2 Ko" 

echo "création /mnt/storfactory/zone$no_zone"
mkdir /mnt/storfactory/zone$no_zone

echo "mkfs -t ext2 /dev/virtualiseur/zone$no_zone"
mkfs -t ext2 /dev/virtualiseur/zone$no_zone

echo "mount -t ext2 /dev/virtualiseur/zone$no_zone /mnt/storfactory/zone$no_zone"
mount -t ext2 /dev/virtualiseur/zone$no_zone /mnt/storfactory/zone$no_zone
