#!/bin/sh
cd /root/DEV_VERSION/scimapdev_controleur_v1.5/smd_scripts/device_hd
rmmod virtualiseur
rmmod scimapdev
#killall smd_commandd

# démontage et effacement des répertoires
cd /mnt/storfactory
for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
do
if [ -d zone$i ] 
then
echo détruit la zone$i
/root/DEV_VERSION/scimapdev_controleur_v1.5/smd_scripts/device_hd/del_zone $i
fi
done

cd /root/DEV_VERSION/scimapdev_controleur_v1.5/smd_scripts/device_hd
#./arreter_brique_hd sam3
#./arreter_brique_hd sam2
./arreter_brique_hd sam4
./arreter_brique_hd sam1
