/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.notify.conf 10110 2004-04-15 12:29:19Z dts12 $
 */
#ifndef MIB_NOTIFY_H
#define MIB_NOTIFY_H

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>

typedef struct {
    u_char* buffer;
    int size;
} trap_var_t;


/* function declarations */
int send_exaDiskGroupStatusNotification_trap(void);
int send_exaDiskStatusNotification_trap(void);
int send_exaFilesystemStatusNotification_trap(void);
int send_exaNodeStatusNotification_trap(void);

#endif /* MIB_NOTIFY_H */
