/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.notify.conf 10110 2004-04-15 12:29:19Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "mib_notify.h"

trap_var_t* trap_vars = NULL;

static const oid snmptrap_oid[] = {1, 3, 6, 1, 6, 3, 1, 1, 4, 1, 0};

int
send_exaDiskGroupStatusNotification_trap( void )
{
    int i = 0;
    u_char * snmp_var_buffer = NULL;
    int snmp_var_size = 0;

    netsnmp_variable_list  *var_list = NULL;
    oid exaDiskGroupStatusNotification_oid[] = { 1,3,6,1,4,1,30730,0,1 };
    oid exaDiskGroupUUID_oid[] = { 1,3,6,1,4,1,30730,1,2,1,1, /* insert index here */ };
    oid exaDiskGroupName_oid[] = { 1,3,6,1,4,1,30730,1,2,1,2, /* insert index here */ };
    oid exaDiskGroupStatus_oid[] = { 1,3,6,1,4,1,30730,1,2,1,3, /* insert index here */ };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, OID_LENGTH(snmptrap_oid),
        ASN_OBJECT_ID,
	(u_char *) exaDiskGroupStatusNotification_oid, sizeof(exaDiskGroupStatusNotification_oid));

    /*
     * Add any objects from the trap definition
     */
    snmp_var_buffer = NULL;
    snmp_var_size = 0;
    if ((trap_vars != NULL) && (trap_vars[i].buffer != NULL))
    {
	snmp_var_buffer = trap_vars[i].buffer;
	snmp_var_size = trap_vars[i].size;
    }
    snmp_varlist_add_variable(&var_list,
        exaDiskGroupUUID_oid, OID_LENGTH(exaDiskGroupUUID_oid),
        ASN_OCTET_STR,
        /* Set an appropriate value for exaDiskGroupUUID */
        snmp_var_buffer, snmp_var_size);
    ++i;
    snmp_var_buffer = NULL;
    snmp_var_size = 0;
    if ((trap_vars != NULL) && (trap_vars[i].buffer != NULL))
    {
	snmp_var_buffer = trap_vars[i].buffer;
	snmp_var_size = trap_vars[i].size;
    }
    snmp_varlist_add_variable(&var_list,
        exaDiskGroupName_oid, OID_LENGTH(exaDiskGroupName_oid),
        ASN_OCTET_STR,
        /* Set an appropriate value for exaDiskGroupName */
        snmp_var_buffer, snmp_var_size);
    ++i;
    snmp_var_buffer = NULL;
    snmp_var_size = 0;
    if ((trap_vars != NULL) && (trap_vars[i].buffer != NULL))
    {
	snmp_var_buffer = trap_vars[i].buffer;
	snmp_var_size = trap_vars[i].size;
    }
    snmp_varlist_add_variable(&var_list,
        exaDiskGroupStatus_oid, OID_LENGTH(exaDiskGroupStatus_oid),
        ASN_INTEGER,
        /* Set an appropriate value for exaDiskGroupStatus */
        snmp_var_buffer, snmp_var_size);
    ++i;

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
int
send_exaDiskStatusNotification_trap( void )
{
    int i = 0;
    u_char * snmp_var_buffer = NULL;
    int snmp_var_size = 0;

    netsnmp_variable_list  *var_list = NULL;
    oid exaDiskStatusNotification_oid[] = { 1,3,6,1,4,1,30730,0,2 };
    oid exaDiskUUID_oid[] = { 1,3,6,1,4,1,30730,1,3,1,1, /* insert index here */ };
    oid exaDiskName_oid[] = { 1,3,6,1,4,1,30730,1,3,1,2, /* insert index here */ };
    oid exaDiskStatus_oid[] = { 1,3,6,1,4,1,30730,1,3,1,3, /* insert index here */ };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, OID_LENGTH(snmptrap_oid),
        ASN_OBJECT_ID,
	(u_char *) exaDiskStatusNotification_oid, sizeof(exaDiskStatusNotification_oid));

    /*
     * Add any objects from the trap definition
     */
    snmp_var_buffer = NULL;
    snmp_var_size = 0;
    if ((trap_vars != NULL) && (trap_vars[i].buffer != NULL))
    {
	snmp_var_buffer = trap_vars[i].buffer;
	snmp_var_size = trap_vars[i].size;
    }
    snmp_varlist_add_variable(&var_list,
        exaDiskUUID_oid, OID_LENGTH(exaDiskUUID_oid),
        ASN_OCTET_STR,
        /* Set an appropriate value for exaDiskUUID */
        snmp_var_buffer, snmp_var_size);
    ++i;
    snmp_var_buffer = NULL;
    snmp_var_size = 0;
    if ((trap_vars != NULL) && (trap_vars[i].buffer != NULL))
    {
	snmp_var_buffer = trap_vars[i].buffer;
	snmp_var_size = trap_vars[i].size;
    }
    snmp_varlist_add_variable(&var_list,
        exaDiskName_oid, OID_LENGTH(exaDiskName_oid),
        ASN_OCTET_STR,
        /* Set an appropriate value for exaDiskName */
        snmp_var_buffer, snmp_var_size);
    ++i;
    snmp_var_buffer = NULL;
    snmp_var_size = 0;
    if ((trap_vars != NULL) && (trap_vars[i].buffer != NULL))
    {
	snmp_var_buffer = trap_vars[i].buffer;
	snmp_var_size = trap_vars[i].size;
    }
    snmp_varlist_add_variable(&var_list,
        exaDiskStatus_oid, OID_LENGTH(exaDiskStatus_oid),
        ASN_INTEGER,
        /* Set an appropriate value for exaDiskStatus */
        snmp_var_buffer, snmp_var_size);
    ++i;

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
int
send_exaFilesystemStatusNotification_trap( void )
{
    int i = 0;
    u_char * snmp_var_buffer = NULL;
    int snmp_var_size = 0;

    netsnmp_variable_list  *var_list = NULL;
    oid exaFilesystemStatusNotification_oid[] = { 1,3,6,1,4,1,30730,0,3 };
    oid exaFilesystemUUID_oid[] = { 1,3,6,1,4,1,30730,1,5,1,1, /* insert index here */ };
    oid exaFilesystemName_oid[] = { 1,3,6,1,4,1,30730,1,5,1,2, /* insert index here */ };
    oid exaFilesystemStatus_oid[] = { 1,3,6,1,4,1,30730,1,5,1,3, /* insert index here */ };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, OID_LENGTH(snmptrap_oid),
        ASN_OBJECT_ID,
	(u_char *) exaFilesystemStatusNotification_oid, sizeof(exaFilesystemStatusNotification_oid));

    /*
     * Add any objects from the trap definition
     */
    snmp_var_buffer = NULL;
    snmp_var_size = 0;
    if ((trap_vars != NULL) && (trap_vars[i].buffer != NULL))
    {
	snmp_var_buffer = trap_vars[i].buffer;
	snmp_var_size = trap_vars[i].size;
    }
    snmp_varlist_add_variable(&var_list,
        exaFilesystemUUID_oid, OID_LENGTH(exaFilesystemUUID_oid),
        ASN_OCTET_STR,
        /* Set an appropriate value for exaFilesystemUUID */
        snmp_var_buffer, snmp_var_size);
    ++i;
    snmp_var_buffer = NULL;
    snmp_var_size = 0;
    if ((trap_vars != NULL) && (trap_vars[i].buffer != NULL))
    {
	snmp_var_buffer = trap_vars[i].buffer;
	snmp_var_size = trap_vars[i].size;
    }
    snmp_varlist_add_variable(&var_list,
        exaFilesystemName_oid, OID_LENGTH(exaFilesystemName_oid),
        ASN_OCTET_STR,
        /* Set an appropriate value for exaFilesystemName */
        snmp_var_buffer, snmp_var_size);
    ++i;
    snmp_var_buffer = NULL;
    snmp_var_size = 0;
    if ((trap_vars != NULL) && (trap_vars[i].buffer != NULL))
    {
	snmp_var_buffer = trap_vars[i].buffer;
	snmp_var_size = trap_vars[i].size;
    }
    snmp_varlist_add_variable(&var_list,
        exaFilesystemStatus_oid, OID_LENGTH(exaFilesystemStatus_oid),
        ASN_INTEGER,
        /* Set an appropriate value for exaFilesystemStatus */
        snmp_var_buffer, snmp_var_size);
    ++i;

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
int
send_exaNodeStatusNotification_trap( void )
{
    int i = 0;
    u_char * snmp_var_buffer = NULL;
    int snmp_var_size = 0;

    netsnmp_variable_list  *var_list = NULL;
    oid exaNodeStatusNotification_oid[] = { 1,3,6,1,4,1,30730,0,4 };
    oid exaNodeUUID_oid[] = { 1,3,6,1,4,1,30730,6,1,1, /* insert index here */ };
    oid exaNodeName_oid[] = { 1,3,6,1,4,1,30730,6,1,2, /* insert index here */ };
    oid exaNodeStatus_oid[] = { 1,3,6,1,4,1,30730,6,1,3, /* insert index here */ };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, OID_LENGTH(snmptrap_oid),
        ASN_OBJECT_ID,
	(u_char *) exaNodeStatusNotification_oid, sizeof(exaNodeStatusNotification_oid));

    /*
     * Add any objects from the trap definition
     */
    snmp_var_buffer = NULL;
    snmp_var_size = 0;
    if ((trap_vars != NULL) && (trap_vars[i].buffer != NULL))
    {
	snmp_var_buffer = trap_vars[i].buffer;
	snmp_var_size = trap_vars[i].size;
    }
    snmp_varlist_add_variable(&var_list,
        exaNodeUUID_oid, OID_LENGTH(exaNodeUUID_oid),
        ASN_OCTET_STR,
        /* Set an appropriate value for exaNodeUUID */
        snmp_var_buffer, snmp_var_size);
    ++i;
    snmp_var_buffer = NULL;
    snmp_var_size = 0;
    if ((trap_vars != NULL) && (trap_vars[i].buffer != NULL))
    {
	snmp_var_buffer = trap_vars[i].buffer;
	snmp_var_size = trap_vars[i].size;
    }
    snmp_varlist_add_variable(&var_list,
        exaNodeName_oid, OID_LENGTH(exaNodeName_oid),
        ASN_OCTET_STR,
        /* Set an appropriate value for exaNodeName */
        snmp_var_buffer, snmp_var_size);
    ++i;
    snmp_var_buffer = NULL;
    snmp_var_size = 0;
    if ((trap_vars != NULL) && (trap_vars[i].buffer != NULL))
    {
	snmp_var_buffer = trap_vars[i].buffer;
	snmp_var_size = trap_vars[i].size;
    }
    snmp_varlist_add_variable(&var_list,
        exaNodeStatus_oid, OID_LENGTH(exaNodeStatus_oid),
        ASN_INTEGER,
        /* Set an appropriate value for exaNodeStatus */
        snmp_var_buffer, snmp_var_size);
    ++i;

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
