#
# Copyright 2002, 2009 Seanodes Ltd http://www.seanodes.com. All rights
# reserved and protected by French, UK, U.S. and other countries' copyright laws.
# This file is part of Exanodes project and is subject to the terms
# and conditions defined in the LICENSE file which is present in the root
# directory of the project.
#

use File::Compare;
use File::Basename;

my $SELF = basename($0);

my $PLATFORM = $^O;
chomp($PLATFORM);
my $DEV_NULL = $PLATFORM eq "MSWin32" ? "nul" : "/dev/null";

$ENV{LC_ALL} = "C";

my $DATE_ENT_FILE = "date.ent";

if (scalar(@ARGV) != 1) {
    print STDERR "Generate the ${DATE_ENT_FILE} file in the current directory.\n";
    print STDERR "The file is used by the Docbook documentation.\n";
    print STDERR "Usage: ${SELF} <versioned source directory>\n";
    exit 1;
}

my $SRCDIR = $ARGV[0];

exit(0) if system("git --version > $DEV_NULL") != 0;

if (! -d "$SRCDIR/.git") {
    print STDERR "error: '${SRCDIR}' is not a versioned source directory\n";
    exit 1;
}

# compute the branch/tag
my $CHANGED_DATE = `cd $SRCDIR && git log -1 --format=%cd`;
chomp($CHANGED_DATE);

$CHANGED_YEAR = $CHANGED_DATE;
$CHANGED_YEAR =~ s/-.*$//;

print "Last Change Date: $CHANGED_DATE\n";

my $new_content = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
$new_content   .= "<!-- Automagically generated by generate_date_ent.pl -->\n";
$new_content   .= "<!ENTITY date '$CHANGED_DATE'>\n";
$new_content   .= "<!ENTITY year '$CHANGED_YEAR'>\n";

my $old_content;
open(OLD_FILE, "<", "$DATE_ENT_FILE");
read(OLD_FILE, $old_content, 1024);
close(OLD_FILE);

if ($new_content eq $old_content) {
    print "$DATE_ENT_FILE has not changed\n";
}
else {
    open(NEW_FILE, ">", "$DATE_ENT_FILE");
    print(NEW_FILE $new_content);
    close(NEW_FILE);
}
