#
# Copyright 2002, 2009 Seanodes Ltd http://www.seanodes.com. All rights
# reserved and protected by French, UK, U.S. and other countries' copyright laws.
# This file is part of Exanodes project and is subject to the terms
# and conditions defined in the LICENSE file which is present in the root
# directory of the project.
#

use File::Compare;

my $PLATFORM = $^O;
chomp($PLATFORM);
my $DEV_NULL = $PLATFORM eq "MSWin32" ? "nul" : "/dev/null";

$ENV{LC_ALL} = "C";

my $GIT_H = "git.h";
my $SRCDIR = $ARGV[0];

exit(0) if system("git --version > $DEV_NULL") != 0;

if (-d "$SRCDIR/.git")
{
    # compute the branch/tag
    # compute the revision number
    # We take the sha1 number of the last commit on the current branch
    my $REVISION = `cd $SRCDIR && git rev-parse --short HEAD`;
    chomp($REVISION);
    $REVISION =~ s/.*://;
    print("revision=$REVISION\n");
    my $new_content = "/* Automagically generated by generate_git_h.pl */\n\n";
    $new_content .= "#define GIT_REVISION   \"$REVISION\"\n";
    my $old_content;
    open(OLD_FILE, "<", "$GIT_H");
    read(OLD_FILE, $old_content, 1024);
    close(OLD_FILE);
    if ($new_content eq $old_content)
    {
        print("$GIT_H has not changed\n");
    }
    else
    {
        open(NEW_FILE, ">", "$GIT_H");
        print(NEW_FILE $new_content);
        close(NEW_FILE);
    }
}
else
{
    print("Not a git working dir\n");
}
